#!/bin/sh
# [Gedit Tool]
# Name=do shell
# Shortcut=<Primary>1
# Languages=
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=all

set -eu
G=$GEDIT_CURRENT_DOCUMENT_PATH
echo : $G
case ${G##*.} in
"coffee") coffee $G;;
"sh") chmod +x $G; $G;;
*) echo "Unbekannter script-typ" ${G##*.}: $G
esac
