#!/bin/sh
# [Gedit Tool]
# Name=make with autosave
# Shortcut=<Primary>2
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=all

set -eu
EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$GEDIT_CURRENT_DOCUMENT_DIR
while test "$DIR" != "/"; do
    for m in GNUmakefile makefile Makefile; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" | sed "s#$EHOME#~#" > /dev/stderr
            sed -i.bak "s/    /\t/" "${DIR}/${m}"
            make -C "${DIR}"
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
echo "No Makefile found!" > /dev/stderr
