#!/bin/sh
# [Gedit Tool]
# Name=xterm shell
# Shortcut=<Primary>3
# Languages=sh
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=all

set -eu
echo : $GEDIT_CURRENT_DOCUMENT_PATH
chmod +x $GEDIT_CURRENT_DOCUMENT_PATH
xterm -e $GEDIT_CURRENT_DOCUMENT_PATH &
